### ISSUE TITLE
Allow usage of `${CONDA_PREFIX}/etc/glvnd/egl_vendor.d`

### ISSUE THREAD

**Issue by ehfd** [conda-forge/libglvnd-feedstock#3]
### Comment:

CC @hmaarrfk @traversaro @isuruf 

https://github.com/conda-forge/ocl-icd-feedstock and https://github.com/conda-forge/ocl-icd-system-feedstock allow using a prefix path for OpenCL's ICD files.

It seems that when a path including `${PREFIX}` is used for https://github.com/conda-forge/ocl-icd-feedstock/blob/main/recipe/build.sh, Conda's compiler somehow translates it into `${CONDA_PREFIX}`.
However, I am unsure of the mechanism by which this works and how it will be applicable for Meson (https://github.com/conda-forge/libglvnd-feedstock/blob/main/recipe/libglvnd_look_for_egl_icd_in_system_location.patch) instead of autoconf.

If possible, https://github.com/conda-forge/ocl-icd-feedstock/blob/main/recipe/check_icds_recursively.diff should not be necessary because multiple directories can be specified in https://github.com/conda-forge/libglvnd-feedstock/blob/main/recipe/libglvnd_look_for_egl_icd_in_system_location.patch.

Anyone who can properly explain how this would work and/or contribute a patch would be extremely thankful.

**Comment by traversaro** [comment]
I think what is happening is that the `ocl-icd` case hardcodes the conda prefix location used at build time, and then during conda installation this hardcoded install path is substituted with the actual `${CONDA_PREFIX}` thanks to the conda support for automatically making binary that have harcoded location of the install path relocatable at least on macOS and Linux (see https://docs.conda.io/projects/conda-build/en/latest/resources/make-relocatable.html).  I am not a big fan in general of this mechanism as sometimes it fails in subtle ways, but if it works fine it can be used in this context (as this library anyhow is only used on Linux).

**Comment by ehfd** [comment]
@traversaro Thanks! Then, I understand this has to do with the `detect_binary_files_with_prefix` option, then?

**Comment by traversaro** [comment]
If we do not want to reply on patching of binaries done by conda, perhaps we can set the `__EGL_VENDOR_LIBRARY_DIRS` env variable, see https://github.com/NVIDIA/libglvnd/blob/master/src/EGL/icd_enumeration.md#icd-discovery ? I did not checked all the possible corner cases, but it may be something we may want to consider.

**Comment by traversaro** [comment]
> [@traversaro](https://github.com/traversaro) Thanks! Then, I understand this has to do with the `detect_binary_files_with_prefix` option, then?

I think it works even out of the box without setting any specific option in conda-build, but I may be wrong on this (I would need to double check). Anyhow, the patching is typically reported with a clear message in conda-build, so you can check that output.

**Comment by ehfd** [comment]
`__EGL_VENDOR_LIBRARY_DIRS` pretty much could also work but may interact with users changing it. I think that a sensible non-environment variable default should also be specified by default as the patch shouldn't be anything immense if all I should do is add:

```
join_paths(get_option('prefix'),get_option('datadir')))
```

**Comment by hmaarrfk** [comment]
Great work you two
